apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-29858-0
  labels:
    storageos.com/hint.master: "gke-c-qzfzd-default-0-f99b6619-g7w5"
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-29858-1
  labels:
    storageos.com/hint.master: "gke-c-qzfzd-default-0-f99b6619-g7w5"
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-29858-2
  labels:
    storageos.com/hint.master: "gke-c-qzfzd-default-0-f99b6619-g7w5"
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-29858-3
  labels:
    storageos.com/hint.master: "gke-c-qzfzd-default-0-f99b6619-g7w5"
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fio-4vol
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: fio
        image: senax/docker-fio:latest
        command:
          - "fio"
          - "/tmp/profile-4vol.fio"
        volumeMounts:
          - name: fio-conf
            mountPath: /tmp/
          - name: vol0
            mountPath: /mnt/pvc0
          - name: vol1
            mountPath: /mnt/pvc1
          - name: vol2
            mountPath: /mnt/pvc2
          - name: vol3
            mountPath: /mnt/pvc3
        resources:
          requests:
            cpu: 500m
      volumes:
      - name: fio-conf
        configMap:
          name: fio-profiles-local
      - name: vol0
        persistentVolumeClaim:
          claimName: pvc-29858-0
      - name: vol1
        persistentVolumeClaim:
          claimName: pvc-29858-1
      - name: vol2
        persistentVolumeClaim:
          claimName: pvc-29858-2
      - name: vol3
        persistentVolumeClaim:
          claimName: pvc-29858-3
